export const Hosts = [
    {
      "City": "Athens",
      "Country": "Greece",
      "Continent": "Europe",
      "Summer (Olympiad)": "I",
      "Winter": "-",
      "Year": 1896,
      "Opening Ceremony": "6-Apr",
      "Closing Ceremony": "15-Apr",
      "Season": "Summer",
      "Lat": 37.9838096,
      "Long": 23.7275388
    },
    {
      "City": "Paris",
      "Country": "France",
      "Continent": "Europe",
      "Summer (Olympiad)": "II",
      "Winter": "-",
      "Year": 1900,
      "Opening Ceremony": "14-May",
      "Closing Ceremony": "28-Oct",
      "Season": "Summer",
      "Lat": 48.856614,
      "Long": 2.3522219
    },
    {
      "City": "St. Louis",
      "Country": "United States",
      "Continent": "North America",
      "Summer (Olympiad)": "III",
      "Winter": "-",
      "Year": 1904,
      "Opening Ceremony": "1-Jul",
      "Closing Ceremony": "23-Nov",
      "Season": "Summer",
      "Lat": 38.6270025,
      "Long": -90.1994042
    },
    {
      "City": "London",
      "Country": "United Kingdom",
      "Continent": "Europe",
      "Summer (Olympiad)": "IV",
      "Winter": "-",
      "Year": 1908,
      "Opening Ceremony": "27-Apr",
      "Closing Ceremony": "31-Oct",
      "Season": "Summer",
      "Lat": 51.5073509,
      "Long": -0.1277583
    },
    {
      "City": "Stockholm",
      "Country": "Sweden",
      "Continent": "Europe",
      "Summer (Olympiad)": "V",
      "Winter": "-",
      "Year": 1912,
      "Opening Ceremony": "5-May",
      "Closing Ceremony": "22-Jul",
      "Season": "Summer",
      "Lat": 59.3293235,
      "Long": 18.0685808
    },
    {
      "City": "Berlin",
      "Country": "Germany",
      "Continent": "Europe",
      "Summer (Olympiad)": "VI",
      "Winter": "-",
      "Year": 1916,
      "Opening Ceremony": "Cancelled due to World War I",
      "Closing Ceremony": "",
      "Season": "Null",
      "Lat": 52.5200066,
      "Long": 13.404954
    },
    {
      "City": "Antwerp",
      "Country": "Belgium",
      "Continent": "Europe",
      "Summer (Olympiad)": "VII",
      "Winter": "-",
      "Year": 1920,
      "Opening Ceremony": "20-Apr",
      "Closing Ceremony": "12-Sep",
      "Season": "Summer",
      "Lat": 51.2194475,
      "Long": 4.4024643
    },
    {
      "City": "Chamonix",
      "Country": "France",
      "Continent": "Europe",
      "Summer (Olympiad)": "-",
      "Winter": "I",
      "Year": 1924,
      "Opening Ceremony": "25-Jan",
      "Closing Ceremony": "4-Feb",
      "Season": "Winter",
      "Lat": 45.923697,
      "Long": 6.869433
    },
    {
      "City": "Paris",
      "Country": "France",
      "Continent": "Europe",
      "Summer (Olympiad)": "VIII",
      "Winter": "-",
      "Year": 1924,
      "Opening Ceremony": "4-May",
      "Closing Ceremony": "27-Jul",
      "Season": "Summer",
      "Lat": 48.856614,
      "Long": 2.3522219
    },
    {
      "City": "St. Moritz",
      "Country": "Switzerland",
      "Continent": "Europe",
      "Summer (Olympiad)": "-",
      "Winter": "II",
      "Year": 1928,
      "Opening Ceremony": "11-Feb",
      "Closing Ceremony": "19-Feb",
      "Season": "Winter",
      "Lat": 46.4907973,
      "Long": 9.8355079
    },
    {
      "City": "Amsterdam",
      "Country": "Netherlands",
      "Continent": "Europe",
      "Summer (Olympiad)": "IX",
      "Winter": "-",
      "Year": 1928,
      "Opening Ceremony": "17-May",
      "Closing Ceremony": "12-Aug",
      "Season": "Summer",
      "Lat": 52.3679843,
      "Long": 4.9035614
    },
    {
      "City": "Lake Placid",
      "Country": "United States",
      "Continent": "North America",
      "Summer (Olympiad)": "-",
      "Winter": "III",
      "Year": 1932,
      "Opening Ceremony": "4-Feb",
      "Closing Ceremony": "15-Feb",
      "Season": "Winter",
      "Lat": 44.2794911,
      "Long": -73.9798713
    },
    {
      "City": "Los Angeles",
      "Country": "United States",
      "Continent": "North America",
      "Summer (Olympiad)": "X",
      "Winter": "-",
      "Year": 1932,
      "Opening Ceremony": "30-Jul",
      "Closing Ceremony": "14-Aug",
      "Season": "Summer",
      "Lat": 34.0522342,
      "Long": -118.2436849
    },
    {
      "City": "Garmisch-Partenkirchen",
      "Country": "Nazi Germany",
      "Continent": "Europe",
      "Summer (Olympiad)": "-",
      "Winter": "IV",
      "Year": 1936,
      "Opening Ceremony": "6-Feb",
      "Closing Ceremony": "16-Feb",
      "Season": "Winter",
      "Lat": 47.4916945,
      "Long": 11.0954984
    },
    {
      "City": "Berlin",
      "Country": "Nazi Germany",
      "Continent": "Europe",
      "Summer (Olympiad)": "XI",
      "Winter": "-",
      "Year": 1936,
      "Opening Ceremony": "1-Aug",
      "Closing Ceremony": "16-Aug",
      "Season": "Summer",
      "Lat": 52.5200066,
      "Long": 13.404954
    },
    {
      "City": "Sapporo",
      "Country": "Empire of Japan",
      "Continent": "Asia",
      "Summer (Olympiad)": "-",
      "Winter": "V",
      "Year": 1940,
      "Opening Ceremony": "Cancelled due to World War II",
      "Closing Ceremony": "Cancelled due to World War II",
      "Season": "Null",
      "Lat": 43.0620958,
      "Long": 141.3543763
    },
    {
      "City": "Garmisch-Partenkirchen",
      "Country": "Germany",
      "Continent": "Europe",
      "Summer (Olympiad)": "-",
      "Winter": "V",
      "Year": 1940,
      "Opening Ceremony": "Cancelled due to World War II",
      "Closing Ceremony": "Cancelled due to World War II",
      "Season": "Null",
      "Lat": 47.4916945,
      "Long": 11.0954984
    },
    {
      "City": "Tokyo",
      "Country": "Japan",
      "Continent": "Asia",
      "Summer (Olympiad)": "XII",
      "Winter": "-",
      "Year": 1940,
      "Opening Ceremony": "Cancelled due to World War II",
      "Closing Ceremony": "Cancelled due to World War II",
      "Season": "Null",
      "Lat": 35.6894875,
      "Long": 139.6917064
    },
    {
      "City": "Helsinki",
      "Country": "Finland",
      "Continent": "Europe",
      "Summer (Olympiad)": "XII",
      "Winter": "-",
      "Year": 1940,
      "Opening Ceremony": "Cancelled due to World War II",
      "Closing Ceremony": "Cancelled due to World War II",
      "Season": "Null",
      "Lat": 60.1698557,
      "Long": 24.9383791
    },
    {
      "City": "Cortina d'Ampezzo",
      "Country": "Italy",
      "Continent": "Europe",
      "Summer (Olympiad)": "-",
      "Winter": "V",
      "Year": 1944,
      "Opening Ceremony": "Cancelled due to World War II",
      "Closing Ceremony": "Cancelled due to World War II",
      "Season": "Null",
      "Lat": 46.5404711,
      "Long": 12.1356524
    },
    {
      "City": "London",
      "Country": "United Kingdom",
      "Continent": "Europe",
      "Summer (Olympiad)": "XIII",
      "Winter": "-",
      "Year": 1944,
      "Opening Ceremony": "Cancelled due to World War II",
      "Closing Ceremony": "Cancelled due to World War II",
      "Season": "Null",
      "Lat": 51.5073509,
      "Long": -0.1277583
    },
    {
      "City": "St. Moritz",
      "Country": "Switzerland",
      "Continent": "Europe",
      "Summer (Olympiad)": "-",
      "Winter": "V",
      "Year": 1948,
      "Opening Ceremony": "30-Jan",
      "Closing Ceremony": "8-Feb",
      "Season": "Winter",
      "Lat": 46.4907973,
      "Long": 9.8355079
    },
    {
      "City": "London",
      "Country": "United Kingdom",
      "Continent": "Europe",
      "Summer (Olympiad)": "XIV",
      "Winter": "-",
      "Year": 1948,
      "Opening Ceremony": "29-Jul",
      "Closing Ceremony": "14-Aug",
      "Season": "Summer",
      "Lat": 51.5073509,
      "Long": -0.1277583
    },
    {
      "City": "Oslo",
      "Country": "Norway",
      "Continent": "Europe",
      "Summer (Olympiad)": "-",
      "Winter": "VI",
      "Year": 1952,
      "Opening Ceremony": "14-Feb",
      "Closing Ceremony": "25-Feb",
      "Season": "Winter",
      "Lat": 59.9138688,
      "Long": 10.7522454
    },
    {
      "City": "Helsinki",
      "Country": "Finland",
      "Continent": "Europe",
      "Summer (Olympiad)": "XV",
      "Winter": "-",
      "Year": 1952,
      "Opening Ceremony": "19-Jul",
      "Closing Ceremony": "3-Aug",
      "Season": "Summer",
      "Lat": 60.1698557,
      "Long": 24.9383791
    },
    {
      "City": "Cortina d'Ampezzo",
      "Country": "Italy",
      "Continent": "Europe",
      "Summer (Olympiad)": "-",
      "Winter": "VII",
      "Year": 1956,
      "Opening Ceremony": "26-Jan",
      "Closing Ceremony": "5-Feb",
      "Season": "Winter",
      "Lat": 46.5404711,
      "Long": 12.1356524
    },
    {
      "City": "Melbourne",
      "Country": null,
      "Continent": "Oceania",
      "Summer (Olympiad)": "XVI",
      "Winter": "-",
      "Year": 1956,
      "Opening Ceremony": "June 10",
      "Closing Ceremony": "June 17",
      "Season": "Summer",
      "Lat": -37.8136276,
      "Long": 144.9630576
    },
    {
      "City": "Squaw Valley",
      "Country": "United States",
      "Continent": "North America",
      "Summer (Olympiad)": "-",
      "Winter": "VIII",
      "Year": 1960,
      "Opening Ceremony": "18-Feb",
      "Closing Ceremony": "28-Feb",
      "Season": "Winter",
      "Lat": 59.3293235,
      "Long": 18.0685808
    },
    {
      "City": "Rome",
      "Country": "Italy",
      "Continent": "Europe",
      "Summer (Olympiad)": "XVII",
      "Winter": "-",
      "Year": 1960,
      "Opening Ceremony": "25-Aug",
      "Closing Ceremony": "11-Sep",
      "Season": "Summer",
      "Lat": 41.9027835,
      "Long": 12.4963655
    },
    {
      "City": "Innsbruck",
      "Country": "Austria",
      "Continent": "Europe",
      "Summer (Olympiad)": "-",
      "Winter": "IX",
      "Year": 1964,
      "Opening Ceremony": "29-Jan",
      "Closing Ceremony": "9-Feb",
      "Season": "Winter",
      "Lat": 47.2692124,
      "Long": 11.4041024
    },
    {
      "City": "Tokyo",
      "Country": "Japan",
      "Continent": "Asia",
      "Summer (Olympiad)": "XVIII",
      "Winter": "-",
      "Year": 1964,
      "Opening Ceremony": "10-Oct",
      "Closing Ceremony": "24-Oct",
      "Season": "Summer",
      "Lat": 35.6894875,
      "Long": 139.6917064
    },
    {
      "City": "Grenoble",
      "Country": "France",
      "Continent": "Europe",
      "Summer (Olympiad)": "-",
      "Winter": "X",
      "Year": 1968,
      "Opening Ceremony": "6-Feb",
      "Closing Ceremony": "18-Feb",
      "Season": "Winter",
      "Lat": 45.188529,
      "Long": 5.724524
    },
    {
      "City": "Mexico City",
      "Country": "Mexico",
      "Continent": "North America",
      "Summer (Olympiad)": "XIX",
      "Winter": "-",
      "Year": 1968,
      "Opening Ceremony": "12-Oct",
      "Closing Ceremony": "27-Oct",
      "Season": "Summer",
      "Lat": 19.4326077,
      "Long": -99.133208
    },
    {
      "City": "Sapporo",
      "Country": "Japan",
      "Continent": "Asia",
      "Summer (Olympiad)": "-",
      "Winter": "XI",
      "Year": 1972,
      "Opening Ceremony": "3-Feb",
      "Closing Ceremony": "13-Feb",
      "Season": "Winter",
      "Lat": 43.0620958,
      "Long": 141.3543763
    },
    {
      "City": "Munich",
      "Country": "West Germany",
      "Continent": "Europe",
      "Summer (Olympiad)": "XX",
      "Winter": "-",
      "Year": 1972,
      "Opening Ceremony": "26-Aug",
      "Closing Ceremony": "11-Sep",
      "Season": "Summer",
      "Lat": 48.1351253,
      "Long": 11.5819805
    },
    {
      "City": "Innsbruck",
      "Country": "Austria",
      "Continent": "Europe",
      "Summer (Olympiad)": "-",
      "Winter": "XII",
      "Year": 1976,
      "Opening Ceremony": "4-Feb",
      "Closing Ceremony": "15-Feb",
      "Season": "Winter",
      "Lat": 47.2692124,
      "Long": 11.4041024
    },
    {
      "City": "Montreal",
      "Country": "Canada",
      "Continent": "North America",
      "Summer (Olympiad)": "XXI",
      "Winter": "-",
      "Year": 1976,
      "Opening Ceremony": "17-Jul",
      "Closing Ceremony": "1-Aug",
      "Season": "Summer",
      "Lat": 45.5016889,
      "Long": -73.567256
    },
    {
      "City": "Lake Placid",
      "Country": "United States",
      "Continent": "North America",
      "Summer (Olympiad)": "-",
      "Winter": "XIII",
      "Year": 1980,
      "Opening Ceremony": "12-Feb",
      "Closing Ceremony": "24-Feb",
      "Season": "Winter",
      "Lat": 44.2794911,
      "Long": -73.9798713
    },
    {
      "City": "Moscow",
      "Country": "Soviet Union",
      "Continent": "Europe",
      "Summer (Olympiad)": "XXII",
      "Winter": "-",
      "Year": 1980,
      "Opening Ceremony": "19-Jul",
      "Closing Ceremony": "3-Aug",
      "Season": "Summer",
      "Lat": 55.755826,
      "Long": 37.6172999
    },
    {
      "City": "Sarajevo",
      "Country": "Yugoslavia",
      "Continent": "Europe",
      "Summer (Olympiad)": "-",
      "Winter": "XIV",
      "Year": 1984,
      "Opening Ceremony": "7-Feb",
      "Closing Ceremony": "19-Feb",
      "Season": "Winter",
      "Lat": 43.8562586,
      "Long": 18.4130763
    },
    {
      "City": "Los Angeles",
      "Country": "United States",
      "Continent": "North America",
      "Summer (Olympiad)": "XXIII",
      "Winter": "-",
      "Year": 1984,
      "Opening Ceremony": "28-Jul",
      "Closing Ceremony": "12-Aug",
      "Season": "Summer",
      "Lat": 34.0522342,
      "Long": -118.2436849
    },
    {
      "City": "Calgary",
      "Country": "Canada",
      "Continent": "North America",
      "Summer (Olympiad)": "-",
      "Winter": "XV",
      "Year": 1988,
      "Opening Ceremony": "13-Feb",
      "Closing Ceremony": "28-Feb",
      "Season": "Winter",
      "Lat": 51.0486151,
      "Long": -114.0708459
    },
    {
      "City": "Seoul",
      "Country": "South Korea",
      "Continent": "Asia",
      "Summer (Olympiad)": "XXIV",
      "Winter": "-",
      "Year": 1988,
      "Opening Ceremony": "17-Sep",
      "Closing Ceremony": "2-Oct",
      "Season": "Summer",
      "Lat": 37.566535,
      "Long": 126.9779692
    },
    {
      "City": "Albertville",
      "Country": "France",
      "Continent": "Europe",
      "Summer (Olympiad)": "-",
      "Winter": "XVI",
      "Year": 1992,
      "Opening Ceremony": "8-Feb",
      "Closing Ceremony": "23-Feb",
      "Season": "Winter",
      "Lat": 45.2312337,
      "Long": -93.6687657
    },
    {
      "City": "Barcelona",
      "Country": "Spain",
      "Continent": "Europe",
      "Summer (Olympiad)": "XXV",
      "Winter": "-",
      "Year": 1992,
      "Opening Ceremony": "25-Jul",
      "Closing Ceremony": "9-Aug",
      "Season": "Summer",
      "Lat": 41.3850639,
      "Long": 2.1734035
    },
    {
      "City": "Lillehammer",
      "Country": "Norway",
      "Continent": "Europe",
      "Summer (Olympiad)": "-",
      "Winter": "XVII",
      "Year": 1994,
      "Opening Ceremony": "12-Feb",
      "Closing Ceremony": "27-Feb",
      "Season": "Winter",
      "Lat": 61.1152713,
      "Long": 10.4662306
    },
    {
      "City": "Atlanta",
      "Country": "United States",
      "Continent": "North America",
      "Summer (Olympiad)": "XXVI",
      "Winter": "-",
      "Year": 1996,
      "Opening Ceremony": "19-Jul",
      "Closing Ceremony": "4-Aug",
      "Season": "Summer",
      "Lat": 33.7489954,
      "Long": -84.3879824
    },
    {
      "City": "Nagano",
      "Country": "Japan",
      "Continent": "Asia",
      "Summer (Olympiad)": "-",
      "Winter": "XVIII",
      "Year": 1998,
      "Opening Ceremony": "7-Feb",
      "Closing Ceremony": "22-Feb",
      "Season": "Winter",
      "Lat": 36.6485829,
      "Long": 138.1947709
    },
    {
      "City": "Sydney",
      "Country": "Australia",
      "Continent": "Oceania",
      "Summer (Olympiad)": "XXVII",
      "Winter": "-",
      "Year": 2000,
      "Opening Ceremony": "15-Sep",
      "Closing Ceremony": "1-Oct",
      "Season": "Summer",
      "Lat": -33.8688197,
      "Long": 151.2092955
    },
    {
      "City": "Salt Lake City",
      "Country": "United States",
      "Continent": "North America",
      "Summer (Olympiad)": "-",
      "Winter": "XIX",
      "Year": 2002,
      "Opening Ceremony": "8-Feb",
      "Closing Ceremony": "24-Feb",
      "Season": "Winter",
      "Lat": 40.76078,
      "Long": -111.891045
    },
    {
      "City": "Athens",
      "Country": "Greece",
      "Continent": "Europe",
      "Summer (Olympiad)": "XXVIII",
      "Winter": "-",
      "Year": 2004,
      "Opening Ceremony": "13-Aug",
      "Closing Ceremony": "29-Aug",
      "Season": "Summer",
      "Lat": 37.9838096,
      "Long": 23.7275388
    },
    {
      "City": "Turin",
      "Country": "Italy",
      "Continent": "Europe",
      "Summer (Olympiad)": "-",
      "Winter": "XX",
      "Year": 2006,
      "Opening Ceremony": "10-Feb",
      "Closing Ceremony": "26-Feb",
      "Season": "Winter",
      "Lat": 45.070339,
      "Long": 7.686864
    },
    {
      "City": "Beijing",
      "Country": "China",
      "Continent": "Asia",
      "Summer (Olympiad)": "XXIX",
      "Winter": "-",
      "Year": 2008,
      "Opening Ceremony": "8-Aug",
      "Closing Ceremony": "24-Aug",
      "Season": "Summer",
      "Lat": 39.904202,
      "Long": 116.407394
    },
    {
      "City": "Vancouver",
      "Country": "Canada",
      "Continent": "North America",
      "Summer (Olympiad)": "-",
      "Winter": "XXI",
      "Year": 2010,
      "Opening Ceremony": "12-Feb",
      "Closing Ceremony": "28-Feb",
      "Season": "Winter",
      "Lat": 49.28273,
      "Long": -123.120735
    },
    {
      "City": "London",
      "Country": "United Kingdom",
      "Continent": "Europe",
      "Summer (Olympiad)": "XXX",
      "Winter": "-",
      "Year": 2012,
      "Opening Ceremony": "27-Jul",
      "Closing Ceremony": "12-Aug",
      "Season": "Summer",
      "Lat": 51.5073509,
      "Long": -0.1277583
    },
    {
      "City": "Sochi",
      "Country": "Russia",
      "Continent": "Europe",
      "Summer (Olympiad)": "-",
      "Winter": "XXII",
      "Year": 2014,
      "Opening Ceremony": "7-Feb",
      "Closing Ceremony": "23-Feb",
      "Season": "Winter",
      "Lat": 43.584469,
      "Long": 39.72028
    },
    {
      "City": "Rio de Janeiro",
      "Country": "Brazil",
      "Continent": "South America",
      "Summer (Olympiad)": "XXXI",
      "Winter": "-",
      "Year": 2016,
      "Opening Ceremony": "5-Aug",
      "Closing Ceremony": "21-Aug",
      "Season": "Summer",
      "Lat": -22.906847,
      "Long": -43.172897
    }
  ];